version: "3.8"
services:
  auth:
    build: ./src/auth
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src/auth:/app
  webhooks:
    build: ./src/webhooks
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./src/webhooks:/app
  nginx:
    image: nginx:latest
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/nginx.conf:ro
    # depends_on: 
    #   - auth
    #   - webhooks
    ports: 
      - "8000:80"
