version: "3.8"
services:
  auth:
    build: ./src/auth
    ports:
      - "3000:3000"
    env_file:
     - .env
  webhooks:
    build: ./src/webhooks
    ports:
      - "3001:3001"
    env_file:
     - .env
